@startuml

abstract class Person {
- id : long
- firstname : String
- lastname : String
- age : int
}

class Skiteacher {
- salary : int
}

class Skistudent{
}

class Course{
- id : long
- name : String
- member : int
- aGroup : Group
- teacher : Skiteacher
}

class Booking{
- id : long
- student : Skistudent
- course : Course
}

enum Class {
ANFAENGER
KOENNER
PROFIS
UNBEKANNT
}

Skiteacher "1" *--> "*" Course
Skistudent "1" *--> "*" Booking
Booking "*" *--> "1" Course
Skiteacher --|> Person
Skistudent --|> Person
Course "1" *--> "1" Class
@enduml
